name: Send a telegram
run-name: ${{ github.actor }} sending a telegram
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: make
      run: make telegraph

    - uses: actions/upload-artifact@v4
      with:
        name: telegraph-artifact
        path: |
          telegraph
          *.o

  release:
    needs: build    
    - uses: actions/checkout@v4
      with:
        repository: jvont/telegram-boy
        ref: 'main'
        token: ${{ secrets.TELEGRAPH_TOKEN }}
        fetch-depth: 0

    - name: Clear existing build files
      run: git rm -f *

    - uses: actions/download-artifact@v4
      with:
        name: telegraph-artifact

    - name: Configure git credentials
      run: |
        git config --unset-all http.https://github.com/.extraheader
        git config user.name ${{ github.actor }}
        git config user.email ${{ github.actor_id }}@users.noreply.github.com

    - name: Push build artifacts
      run: |
        git add -f *.o telegraph
        git commit -m "${{ github.event.head_commit.message }}"
        git push -f -u https://token:${{ secrets.TELEGRAPH_TOKEN }}@github.com/jvont/telegram-boy.git main
