name: Send a telegram
run-name: ${{ github.actor }} sending a telegram
on:
  push:
    branches: [ "main" ]
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        repository: jvont/telegram-boy
        ref: 'main'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: configure git
      run: |
        git config user.name ${{ github.actor }}
        git config user.email ${{ github.actor_id }}@users.noreply.github.com

    - name: push build artifacts
      run: |
        echo "beans" >> README.md
        git add -f README.md
        git commit -m "test build"
        git push -f -u origin main
