name: Send a telegram
run-name: ${{ github.actor }} sending a telegram
on:
  push:
    branches: [ "main" ]
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        repository: jvont/telegram-boy
        ref: 'main'

    - name: configure git
      run: |
        git config --global user.name "jvont"
        git config --global user.email "johannvont@gmail.com"

    - name: push build artifacts
      run: |
        echo "beans" >> README.md
        git add -f README.md
        git commit -m "test build"
        git push -f -u origin main
