name: Send a telegram
run-name: ${{ github.actor }} sending a telegram
on:
  push:
    branches: [ "main" ]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: jvont/telegram-boy
        ref: 'main'
        token: ${{ secrets.GITHUB_TOKEN }}
        path: '.'

    - name: make
      run: make telegraph

    # - name: configure git
    #   run: |
    #     git remote set-url origin https://github.com/jvont/telegram-boy.git
    #     git config user.name ${{ github.actor }}
    #     git config user.email ${{ github.actor_id }}@users.noreply.github.com

    - run: ls

    - run: ls ..

    # - name: push build artifacts
    #   run: |
    #     echo "beans" >> README.md
    #     git add -f README.md
    #     git commit -m "test commit"
    #     git push -f -u origin main
