name: Send a telegram
run-name: ${{ github.actor }} sending a telegram
on:
  push:
    branches: [ "main" ]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: jvont/telegram-boy
        ref: 'main'
        token: ${{ github.token }}

    - name: configure git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    
    - name: push build artifacts
      run: |
        echo "beans" >> README.md
        git add -f README.md
        git commit -m "test build"
        git push -f -u origin main
