name: Build and export
run-name: ${{ github.actor }} building and exporting
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: make
      run: make telegraph

  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello, world!"
